### ISSUE TITLE
Notebook not created when "LOCATION" is "Style Guide Home"

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#25]
### Reported URL ###
<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###
TC 1-10

### Reproduction Steps ###
1. Click on Create Menu
2. Click on 'Notebook' domain object
3. Give the Name with Alphabets only
4. Select "LOCATION" as "Style Guide Home"
4. Click 'OK' Button

### Expected Result ###
create notebook in "Style Guide Home" (or error message)

### Actual  Result ###
Notebook not created.

### Screenshots ###

*Paste screenshots here.*

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by sdgun** [comment]
@zjuasmn Your Test Case set has 10 test cases, This is for which one? Only select one label from TC#1 -TC#10, Attach the image

Please add correct labels you haven't assigned any TC 1-10? All of them are taken, I can see Test Cases 71-83 is your assigned ticket?

Eg: In TC 1-10, If TC5, TC8, TC9 FAILS, You have to report 3 bugs. Then you have to update the issue URL in the

**Comment by sdgun** [comment]
Please add correct labels you haven't assigned any TC 1-10? All of them are taken, I can see Test Cases 71-83 is your assigned ticket?

**Comment by zjuasmn** [comment]
@sdgun this is a single issue that prevents creating notebook in a directory and affects all notebook creating test case. I don't think it should be reported as multiple bugs.

**Comment by sdgun** [comment]
@zjuasmn You labelled this issue as TC 1-10, But you are not assigned to any TC 1-10 tickets. They are already taken. If this is not the case please assign correct labels and 'TC Number Set' in the bug report
