### ISSUE TITLE
Start Time & End Time fields are missing

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#26]
### Reported URL ###

<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###

TC 1-10

### Reproduction Steps ###

1. create a new notebook
2. check notebook page

### Expected Result ###

 Search Filter, Show All, Sort Order, Start Time & End time fields should be shown in the notebook page

### Actual  Result ###

 Search Filter, Show All, Sort Order fields are shown, but no Start Time & End time fields.

### Screenshots ###

![image](https://user-images.githubusercontent.com/4462778/33467057-cec39c20-d68c-11e7-8e91-3e96e97bfed4.png)

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by sdgun** [comment]
Please add correct labels you haven't assigned any TC 1-10? All of them are taken, I can see Test Cases 71-83 is your assigned ticket?

**Comment by zjuasmn** [comment]
@sdgun why close my submitted issue? Isn't that a valid issue?

**Comment by sdgun** [comment]
@zjuasmn What is your assigned ticket, please? Now you haven't any active 'Assigned' tickets. You can test only those assigned tickets. Please READ THE SPECIFICATION CAREFULLY BEFORE LOGGIN BUGS'

- First Assign a ticket from 'Open for Pickup' list
- Then Execute the Test Cases
- If you encounter any failed test cases log a ticket and assign (Test Set Number - eg: TC 1-10) and Test Case # (eg: TC#5)
- After completing the Test case set, Update the ticket URLs in the document and then submit the document in the comment area
- Then Change the label to 'Ready for Review'

**Comment by zjuasmn** [comment]
@sdgun There is no rule about creating new ticket when I working on it.

**Comment by sdgun** [comment]
@zjuasmn It is already there from the start. In the spec and in the ticket description itself

**Comment by zjuasmn** [comment]
@sdgun all threads in Testing Phase Questions are after 10:37 am. I already submitted many doc before that.

**Comment by sdgun** [comment]
@zjuasmn Did you go through the Challenge spec https://www.topcoder.com/challenges/30060879/?type=develop&noncache=true&tab=details 

Take a look at point 6 'If you identify any issues of medium or higher severity log them in the repository with the Issue label. It is important to note which test case and on which step the issue occurred.'

![2017-12-01_9-51-23](https://user-images.githubusercontent.com/4592712/33467810-4212bae0-d67d-11e7-9bfd-d601979bb3af.jpg)

When the competition starts all the Test case sets are created on GitHub by will price. Check the ticket description "Log any issues identified to this repository and include the Test Case number as a label on the issue." 

![2017-12-01_9-50-28](https://user-images.githubusercontent.com/4592712/33467824-60123c3c-d67d-11e7-8c50-6301e852572c.jpg)

These are already there when you started this competition. Please read the challenge details before competing

**Comment by zjuasmn** [comment]
@sdgun the word "log" is ambiguous. I already log the issue in uploaded document and change the label in that issue. If what you want is creating a new issue, you should avoid using "log", please use "create new issue".
