### ISSUE TITLE
Right click menu in Objects Context Area is not correct

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#29]
### Reported URL ###

<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###

TC 11-20

### Reproduction Steps ###

1. Press Right click on anywhere in Objects Context Area

### Expected Result ###

1. Options should be listed
2. New NoteBook Entry option should be available to select 

### Actual  Result ###

Only browser default options.

### Screenshots ###

![image](https://user-images.githubusercontent.com/4462778/33467585-6bde4f66-d690-11e7-9bb3-8fc0f3f46a79.png)

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by sdgun** [comment]
TC Issue. Must right click on the Object area not in an empty place, But counting as a valid defect.
