### ISSUE TITLE
Click Object Name n a Notebook Entry should opened in new tab

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#37]
### Reported URL ###
<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###
TC 31-40

### Reproduction Steps ###

1.   Click on Notebook 'Flight1 Monitor' which is available in Object Context   Menu
2. Select a Notebook A1:H99 which has Embed with Snapshot on it   
3. Click on the Object Name which is added in a Notebook Entry

### Expected Result ###

Object should be opened in new tab with all the details

### Actual  Result ###

Object opened in current tab

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by sdgun** [comment]
New tab means new window in the test case. Closing this bug, but counting as a valid one.
