### ISSUE TITLE
Right click menu of embed element is not correct

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#38]
### Reported URL ###
<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###
TC 31-40 TC 41-50

### Reproduction Steps ###

1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select a Notebook Entry which has Embed with Snapshot on it
3. Right click (by Mouse) on the Embed Element

### Expected Result ###

should be a context menu with "View Snapshot", "Remove...", "Remove Snapshot.."

### Actual  Result ###

right click menu is browser default menu. 

### Screenshots ###

![image](https://user-images.githubusercontent.com/4462778/33468566-4de7513a-d698-11e7-97e8-0c0361e6629f.png)

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by mockmew** [comment]
The same issue.

Device: MacBook Pro

OS: macOS High Sierra

Browser: Safari

<img width="1440" alt="screen shot 2017-12-01 at 4 11 22 pm" src="https://user-images.githubusercontent.com/17176123/33475097-1e505d48-d6b8-11e7-8637-033bb1020ffe.png">

**Comment by aniketofficial** [comment]
The same issue has been observerd for TC set 61-70

### TC Number Set ###
 TC 61-70

### Screenshots ###


![screen shot 2017-12-01 at 2 52 08 pm](https://user-images.githubusercontent.com/8258186/33476220-3c5c69c8-d6a7-11e7-8c16-fe44c01cd4f4.png)


### Issue Information ###

Frequency: Everytime

Device: MacBook Air

OS: macOS Sierra

Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sdgun** [comment]
The bug is valid according to the test case steps. Because there is an issue with the test case closing it; But **counted as a valid issue**. No need to fix from application end.
