### ISSUE TITLE
drag & drop from  display layout not working

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#39]
### Reported URL ###
<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###
TC 31-40

### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Drag an object from Display layout and drop it under Existing entry in Notebook

### Expected Result ###

Object Embed with Snapshot should be updated to an existing entry and timestamp should be updated.

### Actual  Result ###

Nothing happens after dropped.

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by sdgun** [comment]
The bug is valid according to the test case steps. Because there is an issue with the test case closing it; But counted as a valid issue. No need to fix from application end.
