### ISSUE TITLE
"View Large" button not existed

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#41]
### Reported URL ###

<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###
TC 41-50

### Reproduction Steps ###
1. Click Object1 (Object with only Embed)

### Expected Result ###
There is  a "View Large" button at Object1 local controls

### Actual  Result ###

No "View Large" button, maybe it means the "enter full screen mode" button?

### Screenshots ###

![image](https://user-images.githubusercontent.com/4462778/33469168-0e8061e0-d69c-11e7-8873-c5b80d3688b7.png)

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by sdgun** [comment]
When you click on the Object name with only Embed link, you can see some items, Hover over it and you will see 'View Large' icon.
![2017-12-06_21-07-50](https://user-images.githubusercontent.com/4592712/33669859-9091f442-dac9-11e7-9820-f1139dd3b221.jpg)
