### ISSUE TITLE
[Windows]- Test Case 25 – No Notification is while drag from context menu onto new notebook entry

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#44]
Summary:
[Windows]- Test Case 25 – No Notification is while drag from context menu onto new notebook entry

### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/
### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select object1 from Object Context Menu, drag from context menu onto new notebook entry
3. Check the timestamp
4. Select object2 from Object Context Menu, drag from context menu onto new notebook entry
5. Check the timestamp
6. Check Notification 'Notebook Entry created'

### Expected Result ###
Notification 'Notebook Entry created' should be shown at the bottom of the screen 
### Actual  Result ###
No Notification is while drag from context menu onto new notebook entry

### Screenshot ###
![image](https://user-images.githubusercontent.com/31862600/33470165-29bf0576-d5fa-11e7-9c05-42e7940e2667.png)

### Issue Information ###

Frequency: Repeated

Device: Widnow

OS: XP

Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/27
