### ISSUE TITLE
No <domain> in create button dropdown menu

### ISSUE THREAD

**Issue by zjuasmn** [topcoderinc/mct-test-case-execution#46]
### Reported URL ###
<http://nasa-mct-notebook.herokuapp.com/>

### TC Number Set ###
TC 61-70

### Reproduction Steps ###

1. Click on create button, the dropdown menu should appear.

### Expected Result ###

There should be  <domain> as notebook option in the dropdown menu. And it will have another “Create” Option at the topmost left pane to add other domain objects inside the notebook.

### Actual  Result ###

No such option.

### Screenshots ###

![image](https://user-images.githubusercontent.com/4462778/33470327-9c8d99f2-d6a2-11e7-8257-bead67ed77c0.png)

### Issue Information ###

Frequency: Every time

Device: iMac

OS: macOS High Sierra

Browser: Chrome v62

**Comment by aniketofficial** [comment]
### Screenshots ###
In drop down menu of <b>Create</b> no option called Domain available.

![screen shot 2017-12-01 at 2 38 39 pm](https://user-images.githubusercontent.com/8258186/33475785-a7b80260-d6a5-11e7-8d50-f308bcde4ee0.png)



### Issue Information ###

Frequency: Everytime

Device: MacBook Air

OS: macOS Sierra

Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
