### ISSUE TITLE
[Windows]- Intermittent Getting save error message prompt while deleting old Entry 

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#47]
Summary:
[Windows]-  Getting save error message prompt while deleting old Entry  (After Deleting wait 40 seconds)

### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/
### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select object1 from Object Context Menu, drag from context menu onto new notebook entry
3. Select object2 from Object Context Menu, drag from context menu onto new notebook entry
4. Delete the old Entry (Object1)
### Screenshot ###
![image](https://user-images.githubusercontent.com/31862600/33470428-8997989a-d5fb-11e7-82ca-5bbe0ec9319f.png)
![image](https://user-images.githubusercontent.com/31862600/33470431-8c09795e-d5fb-11e7-8267-1a472bd8fa45.png)

### Expected Result ###
Entry should be deleted without any error 
### Actual  Result ###
Getting save error message prompt while deleting old Entry 
### Issue Information ###

Frequency: Repeated

Device: Widnow

OS: XP

Browser: Chrome

**Comment by zjuasmn** [comment]
This is not an error message, it is a confirm message.

**Comment by youdare** [comment]
@zjuasmn read the defect

**Comment by sdgun** [comment]
https://www.screencast.com/t/jimChu92F

**Comment by youdare** [comment]
@sdgun , As i mentioned this is an intermittent issue.
You will get this issue at-least 1 time  in 10 times of deletion.

**Comment by sdgun** [comment]
@youdare This happens because TC#28, Step 2 and 4 (Drag and drop items) NOT because of Delete function. You can double check this by drag and drop two items to an existing entry and wait 10-15sec Must be an issue with Save function.

But you can see the object is deleting
