### ISSUE TITLE
'New Folder' button is absent in Save in Notebook.

### ISSUE THREAD

**Issue by ghost** [topcoderinc/mct-test-case-execution#49]
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com

### TC Number Set ###
TC 21-30

### Reproduction Steps ###
Follow steps 1 to 7 for TC#21

### Expected Result ###

'New Folder' button is needed to proceed.

### Actual  Result ###

New Folder button is absent.

### Screenshots ###

![image](https://user-images.githubusercontent.com/20595047/33471358-f82dfcf8-d692-11e7-89d3-56a7d3af8c8f.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 8.1 

Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/33
