### ISSUE TITLE
[Windows]- Test Case 38 –  cropping, inserting text etc are not getting reflected after clicking “Ok” button” in the Annotate shapshot

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#55]
Summary:
[Windows]- Test Case 38 –  cropping, inserting text etc are not getting reflected after clicking “Ok” button” in the Annotate shapshot
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/
### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select a Notebook Entry which has Embed with Snapshot on it
3. Right click (by Mouse) on the Embed Element
4. Select 'View Snapshot' option
5. Click on Annotate button 
6. Select the Annotation (by cropping, inserting text etc) and click ok
### Expected Result ###
[Windows]- Test Case 38 –  cropping, inserting text etc are should  get  reflected after clicking “Ok” button” in the Annotate snapshot
### Actual  Result ###
[Windows]- Test Case 38 –  cropping, inserting text etc are not getting reflected after clicking “Ok” button” in the Annotate shapshot

### Screenshot ###
Actual 
![image](https://user-images.githubusercontent.com/31862600/33472148-3cd67568-d604-11e7-98bc-3bcc03ac6c79.png)

![image](https://user-images.githubusercontent.com/31862600/33472168-539330fc-d604-11e7-93df-f8a1a72b0db3.png)

### Issue Information ###

Frequency: Repeated

Device: Widnow

OS: XP

Browser: Chrome

**Comment by sdgun** [comment]
Working for me
