### ISSUE TITLE
'New Folder' button absent in 'Save in Notebook'

### ISSUE THREAD

**Issue by ghost** [topcoderinc/mct-test-case-execution#56]
### Reported URL ###
*URL where the issue occured, if applicable*

### TC Number Set ###
TC 21-30

### Reproduction Steps ###

1.   Press Right click anywhere in Objects Context Area   
2. Select 'New NoteBook Entry' 
3. Enter text in 'Entry' text box
4. Select 'Link only' from Embed Type dropdown 
5. Try to observe 'New Folder' button in ' Save in Notebook' 

### Expected Result ###

'New Folder' button required to click and proceed.

### Actual  Result ###

'New Folder' button absent.

### Screenshots ###

![image](https://user-images.githubusercontent.com/20595047/33472234-5be16c72-d697-11e7-983a-159250dcba64.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 8.1

Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sdgun** [comment]
#33
