### ISSUE TITLE
Deleting an Existing Notebook entry when an entry exists in the Search field will not clear the search filter input

### ISSUE THREAD

**Issue by basic60** [topcoderinc/mct-test-case-execution#58]
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/

### TC Number Set ###
TC 51-60

### Reproduction Steps ###
1. Click on the 'Flight1 Monitor' (NoteBook name) which is listed in Objects Context Menu
2.  Search for Text which is avaiable in the notebook entries and Do not press enter
3. Do not delete the entry from search field, click on any existing notebook entry and delete it

### Expected Result ###

1. NoteBook should open with all the entries in it and shown in Display layout
2. Screen should filter/search the text and show all the entries which are matching
3. It should clear the search filter input and cease filtering and existing entry should be deleted.

### Actual  Result ###
 Screen filter the text and show all the entries which are matching.The existing entry is deleted.But the search filter input doesn't clear. 

### Screenshots ###

![](https://wx3.sinaimg.cn/mw690/0070cXBNly1fm1ctgkonvj31hc0u0wkt.jpg)
### Issue Information ###

Frequency: Always

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/43
