### ISSUE TITLE
Incorrect Notification message

### ISSUE THREAD

**Issue by ghost** [topcoderinc/mct-test-case-execution#61]
### Reported URL ###
*URL where the issue occured, if applicable*

### TC Number Set ###
TC 21-30

### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select object1 from Object Context Menu, drag from context menu onto new notebook entry
3. Check the timestamp
4. Select object2 from Object Context Menu, drag from context menu onto new notebook entry
5. Check the timestamp
6. Check Notification at the bottom which may take few seconds before appearing.

### Expected Result ###

Notification 'Notebook Entry created' should be shown at the bottom of the screen

### Actual  Result ###

Notification 'Error persisting Flight1 Monitor' is shown at the bottom of the screen.

### Screenshots ###

![image](https://user-images.githubusercontent.com/20595047/33479335-b40f8fda-d6b2-11e7-9da5-b13c0b8ef3f9.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 8.1

Browser:Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/27
