### ISSUE TITLE
Timestamp updation issue in a given scenario

### ISSUE THREAD

**Issue by ghost** [topcoderinc/mct-test-case-execution#62]
### Reported URL ###
*URL where the issue occured, if applicable*

### TC Number Set ###
TC 21-30

### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select object1 from Object Context Menu, drag from context menu onto an existing Entry2
3. Check the timestamp
4. Select object2 from Object Context Menu, drag from context menu onto an existing Entry1
5. Check the timestamp

### Expected Result ###

Timestamp of the complete existing entry should be updated.

### Actual  Result ###

Timestamp of only newly added object is created without updating a timestamp of complete entry into which object is added.

### Screenshots ###

![image](https://user-images.githubusercontent.com/20595047/33479935-fa2547f6-d6b4-11e7-86ec-cb96f056e9ab.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 8.1
Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/36
