### ISSUE TITLE
Notification Mismatch

### ISSUE THREAD

**Issue by ghost** [topcoderinc/mct-test-case-execution#63]
### Reported URL ###
*URL where the issue occured, if applicable*

### TC Number Set ###
TC 21-30

### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Click on object1 from Object Context Menu
3. Check both Notebook and Object shown in Display Layout
4. Create a new entry in Notebook with Link only
5. Check Notification

### Expected Result ###

Notification 'Notebook Entry created' should be shown at the bottom of the screen

### Actual  Result ###

Notification 'Error Persisting Flight1 Monitor' is shown at the bottom of the screen

### Screenshots ###

![image](https://user-images.githubusercontent.com/20595047/33480681-91c6ffda-d6b7-11e7-8d8d-09f8aabbb57e.png)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 8.1

Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/27
