### ISSUE TITLE
[Ipad] – Not able to use MCT Notebook application in Ipad , Application is displaying error message as” There is noting here.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#65]
Summary:
[Ipad] – Not able to use MCT Notebook application in Ipad , Application is displaying error message as” There is noting here.
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/
### Reproduction Steps ###
Pre-Condition:
Launch http://nasa-mct-notebook.herokuapp.com/ in Ipad
### Expected Result ###
[ipad] – Should allow to use MCT Notebook application in mobile 
### Actual  Result ###
[Ipad] – Not able to use MCT Notebook application in Ipad , Application is displaying error message as” There is noting here.
### Screenshot ###
Actual 
![img_0078](https://user-images.githubusercontent.com/31862600/33482465-820712aa-d62c-11e7-9a29-f97253074443.PNG)

### Issue Information ###

Frequency: Repeated

Device: Ipad

OS: IOS

Browser: Safari  and Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/64
