### ISSUE TITLE
Right Click Context Menu not working 

### ISSUE THREAD

**Issue by m-prabhu** [topcoderinc/mct-test-case-execution#66]
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/#/browse/mine/58418286-aaad-48ef-aa07-92956e3ad01b?tc.mode=local&tc.timeSystem=utc&tc.startDelta=1800000&tc.endDelta=0&view=notebook.view

### TC Number Set ###
TC 31-40

### Reproduction Steps ###
1. Visit the above url
2. Click on Notebook 'flight monitor' which is available in Object Context Menu
3. Select a Notebook Entry which has Embed with Snapshot on it
4. Right click on the Embed Element
5. Right Click Menu is not application specific. Only Normal Browser Right Click option displayed

### Expected Result ###

Application Specific Right Click Options should be displayed-
View Snapshot
Annotate Snapshot...
Remove...
Remove Snapshot...
Open in New Tab
Go to Original

### Actual  Result ###
Only Normal Browser Right Click option displayed

### Screenshots ###

![flight monitor - mozilla firefox_297](https://user-images.githubusercontent.com/30400318/33484272-9341dd0c-d6c7-11e7-9b2d-6cb73bd68701.png)

### Issue Information ###

Frequency: always

Device: desktop

OS: windows 7

Browser: firefox 57

**Comment by sdgun** [comment]
The bug is valid according to the test case steps. Because there is an issue with the test case closing it; But **counted as a valid issue**. No need to fix from application end.
