### ISSUE TITLE
Object opens in same TAB. Not in New Tab

### ISSUE THREAD

**Issue by m-prabhu** [topcoderinc/mct-test-case-execution#67]
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/#/browse/mine/74b7687c-9c82-4d4c-9977-3de50966e37c?tc.mode=local&tc.timeSystem=utc&tc.startDelta=1800000&tc.endDelta=0&view=notebook.view

### TC Number Set ###
TC 31-40

### Reproduction Steps ###
1. Visit above url
2. Select a Notebook Entry which has Embed with Snapshot on it
3. Click on the Object Name which is added in a Notebook Entry

### Expected Result ###

Object should be opened in new tab with all the details

### Actual  Result ###

Object opened in same tab with all the details

### Screenshots ###

![test notebook - mozilla firefox_298](https://user-images.githubusercontent.com/30400318/33484746-a7cac1ba-d6c9-11e7-89cf-07e79aedb330.png)

### Issue Information ###

Frequency: always

Device: desktop

OS: windows 7

Browser: firefox 57

**Comment by sdgun** [comment]
New tab means new window in the test case. 
The bug is valid according to the test case steps. Because there is an issue with the test case closing it; But **counted as a valid issue**. No need to fix from application end.
