### ISSUE TITLE
[Windows]- Test Case 41 –  Application is not allowing to Click on 'Annotate' Button and Crop the snapshot  When an Embed doesn't have a Snapshot,

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#74]
Summary:
[Windows]- Test Case 41 –  Application is not allowing to Click on 'Annotate' Button and Crop the snapshot  When an Embed doesn't have a Snapshot,
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/
### Reproduction Steps ###
1. Click on Notebook 'Flight1 Monitor' which is available in Object Context Menu
2. Select a Notebook Entry which has Embed without Snapshot on it
3. click (drop down) on the Embed
4. Select 'Create Snapshot' option
5. Click on 'Annotate' Button 
6. Crop the snapshot and click ok 
### Expected Result ###
Application should allow to Click on 'Annotate' Button and Crop the snapshot . When an Embed doesn't have a Snapshot,
### Actual  Result ###
Application is not allowing to Click on 'Annotate' Button and Crop the snapshot  When an Embed doesn't have a Snapshot,

Its directly adding the snapshot
### Screenshot ###
![image](https://user-images.githubusercontent.com/31862600/33511756-a7e7df76-d6b4-11e7-9bae-b260a9e2a0f5.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: XP

Browser: Chrome

**Comment by sdgun** [comment]
In step 4. Select 'Create Snapshot' option user is creating a snapshot. So after that user can 'Annotate' the created snapshot by Clicking on the drop-down (Blue) arrow > 'Annotate Snapshot' link

**Comment by youdare** [comment]
@sdgun , basic issue is we are not able to use crop, Text after clicking Annotate

We are able to click Annotate button, Issue in Typing

**Comment by sdgun** [comment]
@youdare You stated 

> Application is not allowing to Click on 'Annotate' Button and Crop the snapshot When an Embed doesn't have a Snapshot, Its directly adding the snapshot

- After user added a new snapshot and then click on the drop-down (Blue) arrow > 'Annotate Snapshot') will open a popup window. (Currently, the CROP icon is disabled) Now mark a selection will enable the   CROP tool

![2017-12-06_17-19-55](https://user-images.githubusercontent.com/4592712/33660455-d31aafa4-daa9-11e7-9556-b48d550a925a.jpg)

**Comment by youdare** [comment]
@sdgun, Its valid defect

1. Created New Notebook Entry Embed without link (Embed doesn't have a Snapshot)

2. click (drop down) on the Embed
3.Select 'Create Snapshot' option
![image](https://user-images.githubusercontent.com/31862600/33677127-c64a82f2-dadd-11e7-95ea-7aa973bd31ab.png)
![image](https://user-images.githubusercontent.com/31862600/33677133-ca7ad39a-dadd-11e7-91a5-d7bbb5044a2b.png)

4. I dint get any 'Annotate' Button, Application is just adding Snapshot

This is valid defect , Please Reopen

**Comment by sdgun** [comment]
@youdare I this contest we are paying for test case execution, not for reported bugs. Some steps are missing in TC Document so no need to fix the application here, that is why I have closed this issue.
