### ISSUE TITLE
User is not able to drag an object from the display layout and drop in to new entry in notebook

### ISSUE THREAD

**Issue by mpriyad** [topcoderinc/mct-test-case-execution#76]
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/

### TC Number Set ###
TC 31-40

### Reproduction Steps ###
1. Ensure at least a notebook and an object are present.
2. Select the notebook and the object from the object context menu to be displayed in display layout (Note: https://github.com/topcoderinc/mct-test-case-execution/issues/75)
3. Try to drag the object under an existing entry to update

### Expected Result ###

Existing entry should be updated with object embed and snapshot

### Actual  Result ###

There is no way for the user to drag and drop the object under notebook entry from the display layout.

However, an object can be dragged from the object context menu and dropped under the notebook entry

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/31853532/33511814-d967f4ac-d748-11e7-8e7f-89fec5b5db6c.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 62.0.3202.94 and Mozilla Firefox 57.0

**Comment by mpriyad** [comment]
linked to https://github.com/topcoderinc/mct-test-case-execution/issues/75

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/39
