### ISSUE TITLE
Object details are shown in the same tab, no new tab is opened when an object is selected

### ISSUE THREAD

**Issue by mpriyad** [topcoderinc/mct-test-case-execution#77]
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/

### TC Number Set ###
TC 31-40

### Reproduction Steps ###
1.  Create a notebook and add an notebook entry to it. Drag and drop an object to the entry so that the embed object and snapshot both are present.
2. Select the Notebook Entry which has Embed with Snapshot on it
3. Click on the Object Name which is added in a Notebook Entry

### Expected Result ###

Object should be opened in new tab with all the details

### Actual  Result ###

Object details are shown in the same tab, no new tab is opened.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/31853532/33511853-b55ef3b6-d749-11e7-8a3c-59890186d9c5.png)

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 62.0.3202.94 and Mozilla Firefox 57.0

**Comment by sdgun** [comment]
New tab means new window in the test case. Closing this bug, but counting as a valid one.
