### ISSUE TITLE
[Windows]- Test Case 46 –  View Large Button and Notebook buttons are shown only when we move mouse over the display layout.

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#80]
Summary:
[Windows]- Test Case 46 –  View Large Button and Notebook buttons are shown only when we move mouse over the display layout.
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com/
### Reproduction Steps ###
1. Click Object1 (Object with only Embed)
2. Check View Large button at Object1 local controls
3. Click on View Large Button
### Expected Result ###
View Large Button and Notebook buttons are shown only when we move mouse over the display layout.
### Actual  Result ###
View Large Button and Notebook buttons should be shown as default
### Screenshot ###
Actual:
![image](https://user-images.githubusercontent.com/31862600/33512460-50a97f84-d6c4-11e7-80ef-196ca74ca27b.png)
![image](https://user-images.githubusercontent.com/31862600/33512462-5f4aa0cc-d6c4-11e7-9982-9db19c10f893.png)

Expected:
![image](https://user-images.githubusercontent.com/31862600/33512465-6fbd9c98-d6c4-11e7-8bff-b34b30526fdc.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: XP

Browser: Chrome

**Comment by sdgun** [comment]
Working as expected

**Comment by youdare** [comment]
@sdgun , Just gone through requirement document , Mouse Hover is not mentioned anywhere.
i already attached "Expected" screenshot from requirement.

**Comment by sdgun** [comment]
@youdare I this contest we are paying for test case execution, not for reported bugs. Some steps are missing in TC Document so no need to fix the application here, that is why I have closed this issue.
