### ISSUE TITLE
Test Case 16 - User is able to create the new entry without  Entering the text in “Entry text” box , While Adding a new Entry to the Object Context Menu

### ISSUE THREAD

**Issue by youdare** [topcoderinc/mct-test-case-execution#81]
Summary:
Test Case 16 - User is able to create the new entry without  Entering the text in “Entry text” box , While Adding a new Entry to the Object Context Menu
### Reported URL ###
http://nasa-mct-notebook.herokuapp.com
### TC Number Set ###
 TC 11-20 

### Reproduction Steps ###
1. Press Right click on anywhere in Objects Context Area
2. Check the option 'New NoteBook Entry'
3. Do not Enter the text in Entry text box and select all other required fields then click ok
### Expected Result ###
User should not be able to save the new entry as screen should ask to enter text in Entry text field
### Actual  Result ###
User is able to create the new entry without  Entering the text in “Entry text” box , While Adding a new Entry to the Object Context Menu

### Screenshots ###
![image](https://user-images.githubusercontent.com/31862600/33527113-345b66e0-d871-11e7-9435-d4df8ef08bce.png)
![image](https://user-images.githubusercontent.com/31862600/33527117-461b850e-d871-11e7-9535-f7de291c8235.png)
![image](https://user-images.githubusercontent.com/31862600/33527121-56ba54da-d871-11e7-8806-102b2bd77c0d.png)

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 2010

Browser: Chrome

**Comment by sdgun** [comment]
https://github.com/topcoderinc/mct-test-case-execution/issues/30
